### ISSUE TITLE
undefined symbol: __cxa_throw_bad_array_new_length

### ISSUE THREAD

**Issue by lsha31** [jvkersch/hsmmlearn#39]
I installed hsmmlearn as described and the installation went through. However, when I run the tests, I get 
```
======================================================================
ERROR: hsmmlearn.tests.test_base (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: hsmmlearn.tests.test_base
Traceback (most recent call last):
  File "/home/ano/anaconda3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/ano/anaconda3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/ano/hsmmlearn/hsmmlearn/tests/test_base.py", line 7, in <module>
    from hsmmlearn.base import _viterbi_impl
ImportError: /home/ano/hsmmlearn/hsmmlearn/base.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cxa_throw_bad_array_new_length
```
The same ImportError occurs when I try to import classes such as e.g. GaussianHSMM:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-afdd3f146f00> in <module>()
----> 1 from hsmmlearn.hsmm import MultinomialHSMM

~/anaconda3/lib/python3.6/site-packages/hsmmlearn-0.1.0-py3.6-linux-x86_64.egg/hsmmlearn/hsmm.py in <module>()
      1 import numpy as np
      2 
----> 3 from .base import _viterbi_impl, _fb_impl
      4 from .emissions import GaussianEmissions, MultinomialEmissions
      5 from .properties import Durations, Emissions, TransitionMatrix

ImportError: /home/ano/anaconda3/lib/python3.6/site-packages/hsmmlearn-0.1.0-py3.6-linux-x86_64.egg/hsmmlearn/base.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cxa_throw_bad_array_new_length
```
I am running Python 3.6 and GCC 7.3.1-2 on Fedora 27. Any ideas what I have to change about my build configuration to make this work?

Apart from that: Thanks for the great work!

**Comment by jvkersch** [comment]
@lsha31 Thanks for the report. I think this may be a problem with your toolchain: it's hard to say exactly what but it looks like the shared library is picking up an older version of libstdc++.

You can try running `ldd /home/ano/anaconda3/lib/python3.6/site-packages/hsmmlearn-0.1.0-py3.6-linux-x86_64.egg/hsmmlearn/base.cpython-36m-x86_64-linux-gnu.so` and seeing what it reports for libstdc++. For the record, here's mine:
```
(testpy36)vagrant@vagrant:~/hsmmlearn$ ldd ./hsmmlearn/base.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffdffed4000)
	libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007fd4cb2f2000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd4caf6c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd4cac16000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd4ca9ff000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd4ca61f000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd4ca3f4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd4ca1d7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd4c9fb8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd4c9db4000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fd4c9bb0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd4cbbde000)
```

**Comment by lsha31** [comment]
Updating libstdc++ did indeed fix this. Thank you very much!

**Comment by jvkersch** [comment]
Glad to hear you got it working!
